version: '3.5'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: docker-superindo
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      backendme:
        ipv4_address: 172.28.0.2
    command: ifconfig
  db:
    container_name: superindo-mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=superindo
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backendme:
        ipv4_address: 172.28.0.3
  redis:
    container_name: superindo-redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      backendme:
        ipv4_address: 172.28.0.4

volumes:
  db:
    driver: local

networks:
  backendme:
    driver: bridge
    ipam:
      driver: default
      config:
        -  subnet: 172.28.0.0/16